version: 2
jobs:
    build-node12:
        docker:
            - image: circleci/node:12-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run ci

    build-node10:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run ci

    build-node8:
        docker:
            - image: circleci/node:8-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run ci

workflows:
    version: 2
    build:
        jobs:
            - build-node12
                filters:
                    branches:
                        only:
                            - master
                            - /4\.x/
            - build-node10
                filters:
                    branches:
                        only:
                            - master
                            - /4\.x/
            - build-node8
                filters:
                    branches:
                        only:
                            - master
                            - /4\.x/