// Generated automatically by nearley, version 2.13.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

  function sel(match, indices) {
    return match.map(function(m) {
      var arr = [];
        indices.forEach(function(i) {
          arr.push(m[i]);
        });
        return arr;
    });
  }


// Bypasses TS6133. Allow declared but unused functions.
// @ts-ignore
function nth(n) {
    return function(d) {
        return d[n];
    };
}


// Bypasses TS6133. Allow declared but unused functions.
// @ts-ignore
function $(o) {
    return function(d) {
        var ret = {};
        Object.keys(o).forEach(function(k) {
            ret[k] = d[o[k]];
        });
        return ret;
    };
}
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": function(d) {return null;}},
    {"name": "__$ebnf$1", "symbols": ["wschar"]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": function(d) {return null;}},
    {"name": "wschar", "symbols": [/[ \t\n\v\f]/], "postprocess": id},
    {"name": "Stylesheet", "symbols": ["_", "Root"], "postprocess": $({'Stylesheet': 1})},
    {"name": "Root", "symbols": ["Primary"], "postprocess": d => [d[0]]},
    {"name": "Root", "symbols": ["Root", "_", "Primary"], "postprocess": d => d[0].concat(d[2])},
    {"name": "Primary", "symbols": ["Ruleset"], "postprocess": id},
    {"name": "Primary", "symbols": ["MixinDefinition"], "postprocess": id},
    {"name": "Primary", "symbols": ["MixinCall", "_semi"], "postprocess": $({'MixinCall': 0})},
    {"name": "Primary", "symbols": ["FunctionCall", "_semi"], "postprocess": $({'Call': 0})},
    {"name": "Primary", "symbols": ["VariableDefinition", "_semi"]},
    {"name": "Primary$ebnf$1$subexpression$1", "symbols": ["_semi", "_", "Primary"]},
    {"name": "Primary$ebnf$1", "symbols": ["Primary$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Primary$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Primary", "symbols": ["VariableDefinition", "Primary$ebnf$1"], "postprocess": $({'Variable': 0})},
    {"name": "Primary", "symbols": ["AtRule", "_semi"], "postprocess": $({'AtRule': 0})},
    {"name": "AtRule$ebnf$1", "symbols": ["Block"], "postprocess": id},
    {"name": "AtRule$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "AtRule", "symbols": [{"literal":"@"}, "Ident", "_", /[^:]/, "AtRule$ebnf$1"]},
    {"name": "Ruleset$ebnf$1", "symbols": ["Comment"], "postprocess": id},
    {"name": "Ruleset$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Ruleset", "symbols": ["Ruleset$ebnf$1", "SelectorList", "_", "Block"], "postprocess": d => { return { type: 'Ruleset', comment: d[0], selectors: d[1], rules: d[3]} }},
    {"name": "Block$ebnf$1", "symbols": []},
    {"name": "Block$ebnf$1", "symbols": ["Block$ebnf$1", "Rule"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Block", "symbols": [{"literal":"{"}, "_", "Block$ebnf$1", "_", {"literal":"}"}], "postprocess": d => d[2]},
    {"name": "Rule$ebnf$1$subexpression$1", "symbols": ["_semi", "_", "Rule"]},
    {"name": "Rule$ebnf$1", "symbols": ["Rule$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Rule$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Rule", "symbols": ["Declaration", "Rule$ebnf$1"]},
    {"name": "Rule", "symbols": ["Primary"]},
    {"name": "SelectorList", "symbols": ["Selector"], "postprocess": d => { return [{ type: 'Selector', elements: d[0]}] }},
    {"name": "SelectorList", "symbols": ["SelectorList", "_", {"literal":","}, "_", "Selector"], "postprocess": d => d[0].concat([{ type: 'Selector', elements: d[4]}])},
    {"name": "MixinDefinition$ebnf$1", "symbols": ["Args"], "postprocess": id},
    {"name": "MixinDefinition$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MixinDefinition$ebnf$2$subexpression$1", "symbols": ["Guard", "_"]},
    {"name": "MixinDefinition$ebnf$2", "symbols": ["MixinDefinition$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "MixinDefinition$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MixinDefinition", "symbols": ["ClassOrId", {"literal":"("}, "MixinDefinition$ebnf$1", {"literal":")"}, "_", "MixinDefinition$ebnf$2", "Block"], "postprocess": d => { return { type: 'MixinDefinition', name: d[0], params: d[2], condition: d[4], rules: d[6] } }},
    {"name": "Selector", "symbols": ["Element"], "postprocess": d => [{ type: 'Element', combinator: '', value: d[0]}]},
    {"name": "Selector", "symbols": ["Selector", "__", "Element"], "postprocess": d => d[0].concat([{ type: 'Element', combinator: ' ', value: d[2]} ])},
    {"name": "Selector", "symbols": ["Selector", "_", "Combinator", "_", "Element"], "postprocess": d => d[0].concat([{ type: 'Element', combinator: d[2], value: d[4]}])},
    {"name": "Class", "symbols": [{"literal":"."}, "Ident"], "postprocess": d => d[0] + d[1]},
    {"name": "Id", "symbols": [{"literal":"#"}, "Ident"], "postprocess": d => d[0] + d[1]},
    {"name": "Element", "symbols": ["Class"], "postprocess": id},
    {"name": "Element", "symbols": ["Id"], "postprocess": id},
    {"name": "Element", "symbols": ["Ident"], "postprocess": id},
    {"name": "Element", "symbols": ["Attr"], "postprocess": id},
    {"name": "Element", "symbols": [{"literal":"&"}], "postprocess": id},
    {"name": "Element", "symbols": ["Pseudo"], "postprocess": id},
    {"name": "Element", "symbols": [{"literal":"*"}], "postprocess": id},
    {"name": "Combinator", "symbols": [{"literal":">"}], "postprocess": id},
    {"name": "Combinator", "symbols": [{"literal":"+"}], "postprocess": id},
    {"name": "Combinator", "symbols": [{"literal":"~"}], "postprocess": id},
    {"name": "Combinator", "symbols": [{"literal":"|"}], "postprocess": id},
    {"name": "Combinator$string$1", "symbols": [{"literal":">"}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Combinator", "symbols": ["Combinator$string$1"], "postprocess": id},
    {"name": "Combinator$string$2", "symbols": [{"literal":"|"}, {"literal":"|"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Combinator", "symbols": ["Combinator$string$2"], "postprocess": id},
    {"name": "Combinator$string$3", "symbols": [{"literal":">"}, {"literal":">"}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Combinator", "symbols": ["Combinator$string$3"], "postprocess": id},
    {"name": "Attr$ebnf$1$subexpression$1$ebnf$1", "symbols": [/[|~*$^]/], "postprocess": id},
    {"name": "Attr$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Attr$ebnf$1$subexpression$1$subexpression$1", "symbols": ["Quoted"]},
    {"name": "Attr$ebnf$1$subexpression$1$subexpression$1$ebnf$1", "symbols": [/[^\]]/]},
    {"name": "Attr$ebnf$1$subexpression$1$subexpression$1$ebnf$1", "symbols": ["Attr$ebnf$1$subexpression$1$subexpression$1$ebnf$1", /[^\]]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Attr$ebnf$1$subexpression$1$subexpression$1", "symbols": ["Attr$ebnf$1$subexpression$1$subexpression$1$ebnf$1"]},
    {"name": "Attr$ebnf$1$subexpression$1", "symbols": ["Attr$ebnf$1$subexpression$1$ebnf$1", {"literal":"="}, "Attr$ebnf$1$subexpression$1$subexpression$1"]},
    {"name": "Attr$ebnf$1", "symbols": ["Attr$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Attr$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Attr$ebnf$2$subexpression$1", "symbols": ["_", {"literal":"i"}]},
    {"name": "Attr$ebnf$2", "symbols": ["Attr$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Attr$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Attr", "symbols": [{"literal":"["}, "Ident", "Attr$ebnf$1", "Attr$ebnf$2", {"literal":"]"}]},
    {"name": "Pseudo$ebnf$1", "symbols": [{"literal":":"}], "postprocess": id},
    {"name": "Pseudo$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Pseudo$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "Pseudo$ebnf$2$subexpression$1$ebnf$1", "symbols": ["Pseudo$ebnf$2$subexpression$1$ebnf$1", /[^)]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Pseudo$ebnf$2$subexpression$1", "symbols": [{"literal":"("}, "Pseudo$ebnf$2$subexpression$1$ebnf$1", {"literal":")"}]},
    {"name": "Pseudo$ebnf$2", "symbols": ["Pseudo$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Pseudo$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Pseudo", "symbols": [{"literal":":"}, "Pseudo$ebnf$1", "Ident", "Pseudo$ebnf$2"]},
    {"name": "Extend$string$1", "symbols": [{"literal":":"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Extend$ebnf$1$subexpression$1", "symbols": ["__", "ExtendKeys"]},
    {"name": "Extend$ebnf$1", "symbols": ["Extend$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Extend$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Extend", "symbols": ["Extend$string$1", "_", "SelectorList", "Extend$ebnf$1", {"literal":")"}]},
    {"name": "ExtendKeys$ebnf$1", "symbols": [{"literal":"!"}], "postprocess": id},
    {"name": "ExtendKeys$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ExtendKeys$subexpression$1$string$1", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ExtendKeys$subexpression$1", "symbols": ["ExtendKeys$subexpression$1$string$1"]},
    {"name": "ExtendKeys$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ExtendKeys$subexpression$1", "symbols": ["ExtendKeys$subexpression$1$string$2"]},
    {"name": "ExtendKeys$subexpression$1$string$3", "symbols": [{"literal":"A"}, {"literal":"L"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ExtendKeys$subexpression$1", "symbols": ["ExtendKeys$subexpression$1$string$3"]},
    {"name": "ExtendKeys$subexpression$1$string$4", "symbols": [{"literal":"D"}, {"literal":"E"}, {"literal":"E"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ExtendKeys$subexpression$1", "symbols": ["ExtendKeys$subexpression$1$string$4"]},
    {"name": "ExtendKeys", "symbols": ["ExtendKeys$ebnf$1", "ExtendKeys$subexpression$1"]},
    {"name": "ClassOrId", "symbols": ["Class"], "postprocess": id},
    {"name": "ClassOrId", "symbols": ["Id"], "postprocess": id},
    {"name": "MixinName", "symbols": ["ClassOrId"], "postprocess": $({ MixinName: 0})},
    {"name": "Declaration", "symbols": ["Ident", "_", {"literal":":"}, "_", "Value"]},
    {"name": "VariableDefinition", "symbols": ["Variable", "_", {"literal":":"}, "_", "VariableValue"], "postprocess": d => { return { type: 'Declaration', name: d[0], variable: true, value: d[4]} }},
    {"name": "VariableValue", "symbols": ["Value"]},
    {"name": "VariableValue", "symbols": ["DetachedRuleset"]},
    {"name": "DetachedRuleset", "symbols": ["Block"], "postprocess": d => { return { type: 'DetachedRuleset', ruleset: { type: 'Ruleset', rules: d[0] } }}},
    {"name": "Value$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Value$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"!"}, "_", "Value$ebnf$1$subexpression$1$string$1"]},
    {"name": "Value$ebnf$1", "symbols": ["Value$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Value$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Value", "symbols": ["ExpressionList", "Value$ebnf$1"]},
    {"name": "ExpressionList", "symbols": ["Expression"]},
    {"name": "ExpressionList", "symbols": ["ExpressionList", "_", {"literal":","}, "_", "Expression"]},
    {"name": "Entity", "symbols": ["Comment"]},
    {"name": "Entity", "symbols": ["Literal"]},
    {"name": "Entity", "symbols": ["Url"]},
    {"name": "Entity", "symbols": ["Keyword"]},
    {"name": "Entity", "symbols": [{"literal":"/"}]},
    {"name": "Entity", "symbols": ["Javascript"]},
    {"name": "Literal", "symbols": ["Quoted"]},
    {"name": "Literal", "symbols": ["UnicodeDescriptor"]},
    {"name": "ExpressionParts", "symbols": ["Unit"]},
    {"name": "ExpressionParts", "symbols": ["FunctionCall"]},
    {"name": "ExpressionParts", "symbols": ["Color"]},
    {"name": "ExpressionParts", "symbols": ["Variable"]},
    {"name": "ExpressionParts", "symbols": ["PropReference"]},
    {"name": "Quoted$ebnf$1", "symbols": []},
    {"name": "Quoted$ebnf$1$subexpression$1", "symbols": [/[^\"\n\r]/]},
    {"name": "Quoted$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"\""}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Quoted$ebnf$1$subexpression$1", "symbols": ["Quoted$ebnf$1$subexpression$1$string$1"]},
    {"name": "Quoted$ebnf$1", "symbols": ["Quoted$ebnf$1", "Quoted$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Quoted", "symbols": [{"literal":"\""}, "Quoted$ebnf$1", {"literal":"\""}]},
    {"name": "Quoted$ebnf$2", "symbols": []},
    {"name": "Quoted$ebnf$2$subexpression$1", "symbols": [/[^\'\n\r]/]},
    {"name": "Quoted$ebnf$2$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"'"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Quoted$ebnf$2$subexpression$1", "symbols": ["Quoted$ebnf$2$subexpression$1$string$1"]},
    {"name": "Quoted$ebnf$2", "symbols": ["Quoted$ebnf$2", "Quoted$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Quoted", "symbols": [{"literal":"'"}, "Quoted$ebnf$2", {"literal":"'"}]},
    {"name": "Num$ebnf$1$subexpression$1$ebnf$1", "symbols": ["Int"], "postprocess": id},
    {"name": "Num$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Num$ebnf$1$subexpression$1", "symbols": ["Num$ebnf$1$subexpression$1$ebnf$1", {"literal":"."}]},
    {"name": "Num$ebnf$1", "symbols": ["Num$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Num$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Num", "symbols": ["Num$ebnf$1", "Int"]},
    {"name": "Percentage", "symbols": ["Num", {"literal":"%"}]},
    {"name": "Dimension", "symbols": ["Num", "Ident"]},
    {"name": "Unit$ebnf$1$subexpression$1", "symbols": [{"literal":"%"}]},
    {"name": "Unit$ebnf$1$subexpression$1", "symbols": ["Ident"]},
    {"name": "Unit$ebnf$1", "symbols": ["Unit$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Unit$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Unit", "symbols": ["Num", "Unit$ebnf$1"]},
    {"name": "Keyword$ebnf$1", "symbols": []},
    {"name": "Keyword$ebnf$1", "symbols": ["Keyword$ebnf$1", "AlphaNumDash"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Keyword", "symbols": ["AlphaDash", "Keyword$ebnf$1"]},
    {"name": "ExpressionContainer", "symbols": [{"literal":"("}, "_", "Expression", "_", {"literal":")"}]},
    {"name": "Expression$ebnf$1$subexpression$1", "symbols": ["_", "Operator", "_", "Expression"]},
    {"name": "Expression$ebnf$1", "symbols": ["Expression$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Expression", "symbols": ["ExpressionContainer", "Expression$ebnf$1"]},
    {"name": "Expression$ebnf$2$subexpression$1", "symbols": ["_", "Operator", "_", "Expression"]},
    {"name": "Expression$ebnf$2", "symbols": ["Expression$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Expression", "symbols": ["ExpressionParts", "Expression$ebnf$2"]},
    {"name": "FunctionCall$subexpression$1", "symbols": ["Ident"]},
    {"name": "FunctionCall$subexpression$1", "symbols": [{"literal":"%"}]},
    {"name": "FunctionCall", "symbols": ["FunctionCall$subexpression$1", {"literal":"("}, "Args", {"literal":")"}]},
    {"name": "Assignment", "symbols": ["Keyword", {"literal":"="}, "Value"]},
    {"name": "Url$string$1", "symbols": [{"literal":"u"}, {"literal":"r"}, {"literal":"l"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Url$subexpression$1", "symbols": ["Quoted"]},
    {"name": "Url$subexpression$1$ebnf$1", "symbols": []},
    {"name": "Url$subexpression$1$ebnf$1", "symbols": ["Url$subexpression$1$ebnf$1", /[^)]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Url$subexpression$1", "symbols": ["Url$subexpression$1$ebnf$1"]},
    {"name": "Url", "symbols": ["Url$string$1", "_", "Url$subexpression$1", "_", {"literal":")"}]},
    {"name": "Prop", "symbols": ["PropReference"]},
    {"name": "Prop", "symbols": ["PropReferenceCurly"]},
    {"name": "Var", "symbols": ["Variable"]},
    {"name": "Var", "symbols": ["VariableCurly"]},
    {"name": "Interpolator", "symbols": ["VariableCurly"]},
    {"name": "Interpolator", "symbols": ["PropReferenceCurly"]},
    {"name": "PropReference", "symbols": [{"literal":"$"}, "LessIdent"]},
    {"name": "PropReferenceCurly$string$1", "symbols": [{"literal":"$"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PropReferenceCurly", "symbols": ["PropReferenceCurly$string$1", "LessIdent", {"literal":"}"}]},
    {"name": "Variable$ebnf$1", "symbols": [{"literal":"@"}], "postprocess": id},
    {"name": "Variable$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Variable", "symbols": [{"literal":"@"}, "Variable$ebnf$1", "LessIdent"], "postprocess": d => d.join('')},
    {"name": "VariableCurly$string$1", "symbols": [{"literal":"@"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VariableCurly", "symbols": ["VariableCurly$string$1", "LessIdent", {"literal":"}"}], "postprocess": d => d.join('')},
    {"name": "Color$ebnf$1", "symbols": ["Hex3"], "postprocess": id},
    {"name": "Color$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Color", "symbols": [{"literal":"#"}, "Hex3", "Color$ebnf$1"], "postprocess": d => d.join('')},
    {"name": "UnicodeDescriptor$string$1", "symbols": [{"literal":"U"}, {"literal":"+"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UnicodeDescriptor$ebnf$1", "symbols": [/[0-9a-fA-F?]/]},
    {"name": "UnicodeDescriptor$ebnf$1", "symbols": ["UnicodeDescriptor$ebnf$1", /[0-9a-fA-F?]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "UnicodeDescriptor$ebnf$2$subexpression$1$ebnf$1", "symbols": [/[0-9a-fA-F?]/]},
    {"name": "UnicodeDescriptor$ebnf$2$subexpression$1$ebnf$1", "symbols": ["UnicodeDescriptor$ebnf$2$subexpression$1$ebnf$1", /[0-9a-fA-F?]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "UnicodeDescriptor$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "UnicodeDescriptor$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "UnicodeDescriptor$ebnf$2", "symbols": ["UnicodeDescriptor$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "UnicodeDescriptor$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "UnicodeDescriptor", "symbols": ["UnicodeDescriptor$string$1", "UnicodeDescriptor$ebnf$1", "UnicodeDescriptor$ebnf$2"], "postprocess": d => d.join('')},
    {"name": "Javascript$ebnf$1", "symbols": [{"literal":"~"}], "postprocess": id},
    {"name": "Javascript$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Javascript$ebnf$2", "symbols": []},
    {"name": "Javascript$ebnf$2", "symbols": ["Javascript$ebnf$2", /[^`]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Javascript", "symbols": ["Javascript$ebnf$1", {"literal":"`"}, "Javascript$ebnf$2", {"literal":"`"}]},
    {"name": "MixinCall$ebnf$1$subexpression$1", "symbols": ["ClassOrId", "_", {"literal":">"}, "_"]},
    {"name": "MixinCall$ebnf$1", "symbols": ["MixinCall$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "MixinCall$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MixinCall$ebnf$2$subexpression$1$ebnf$1", "symbols": ["Args"], "postprocess": id},
    {"name": "MixinCall$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MixinCall$ebnf$2$subexpression$1", "symbols": [{"literal":"("}, "MixinCall$ebnf$2$subexpression$1$ebnf$1", {"literal":")"}]},
    {"name": "MixinCall$ebnf$2", "symbols": ["MixinCall$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "MixinCall$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MixinCall", "symbols": ["MixinCall$ebnf$1", "MixinName", "MixinCall$ebnf$2"]},
    {"name": "Args", "symbols": []},
    {"name": "_semi", "symbols": ["_", {"literal":";"}]},
    {"name": "Namespace", "symbols": [{"literal":"5"}]},
    {"name": "Guard", "symbols": [{"literal":"6"}]},
    {"name": "LessIdent$ebnf$1", "symbols": ["AlphaNumDash"]},
    {"name": "LessIdent$ebnf$1", "symbols": ["LessIdent$ebnf$1", "AlphaNumDash"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LessIdent", "symbols": ["LessIdent$ebnf$1"], "postprocess": d => d[0].join('')},
    {"name": "Ident$ebnf$1", "symbols": []},
    {"name": "Ident$ebnf$1", "symbols": ["Ident$ebnf$1", "NameChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Ident", "symbols": ["NameStart", "Ident$ebnf$1"], "postprocess": d => d.join('')},
    {"name": "Operator", "symbols": [{"literal":"*"}]},
    {"name": "Operator", "symbols": [{"literal":"+"}]},
    {"name": "Operator", "symbols": [{"literal":"-"}]},
    {"name": "Operator", "symbols": [{"literal":"/"}]},
    {"name": "Int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "Int$ebnf$1", "symbols": ["Int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Int", "symbols": ["Int$ebnf$1"], "postprocess": d => d.join('')},
    {"name": "Hex3", "symbols": ["Hex", "Hex", "Hex"], "postprocess": d => d.join('')},
    {"name": "Hex", "symbols": [/[a-fA-F0-9]/]},
    {"name": "NameStart", "symbols": [/[a-zA-Z_-]/]},
    {"name": "NameStart", "symbols": ["NonAscii"]},
    {"name": "NameStart", "symbols": ["Escape"]},
    {"name": "NameChar", "symbols": ["AlphaNumDash"]},
    {"name": "NameChar", "symbols": ["NonAscii"]},
    {"name": "NameChar", "symbols": ["Escape"]},
    {"name": "AlphaDash", "symbols": [/[a-zA-Z_-]/]},
    {"name": "AlphaNumDash", "symbols": [/[A-Za-z0-9_-]/]},
    {"name": "NonAscii", "symbols": [/[\u0080-\uD7FF\uE000-\uFFFD]/]},
    {"name": "Escape", "symbols": ["Unicode"]},
    {"name": "Escape", "symbols": [{"literal":"\\"}, /[\u0020-\u007E\u0080-\uD7FF\uE000-\uFFFD]/]},
    {"name": "Unicode$ebnf$1", "symbols": ["Hex"]},
    {"name": "Unicode$ebnf$1", "symbols": ["Unicode$ebnf$1", "Hex"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Unicode", "symbols": [{"literal":"\\"}, "Unicode$ebnf$1"]},
    {"name": "Comment", "symbols": ["_", "Comment", "_"]},
    {"name": "Comment$string$1", "symbols": [{"literal":"/"}, {"literal":"/"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Comment$ebnf$1", "symbols": []},
    {"name": "Comment$ebnf$1", "symbols": ["Comment$ebnf$1", /[^\n\r]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Comment", "symbols": ["Comment$string$1", "Comment$ebnf$1"]},
    {"name": "Comment$string$2", "symbols": [{"literal":"/"}, {"literal":"*"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Comment$ebnf$2", "symbols": []},
    {"name": "Comment$ebnf$2", "symbols": ["Comment$ebnf$2", "CommentChars"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Comment$string$3", "symbols": [{"literal":"*"}, {"literal":"/"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Comment", "symbols": ["Comment$string$2", "Comment$ebnf$2", "Comment$string$3"]},
    {"name": "CommentChars", "symbols": [{"literal":"*"}, /[^\/]/]},
    {"name": "CommentChars", "symbols": [/[^*]/]}
]
  , ParserStart: "Stylesheet"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
